In [41]:
import pandas as pd
data = pd.read_csv('cleaned_data.csv')
data = pd.DataFrame(data)  # Placeholder for the actual data cleaning process
data =data.drop(columns=['Gender', 'Segment', 'nps_category', 'last_interaction_date'])

In [42]:
data

,CustomerID,Age,NPS,account_age_days,age_group,total_purchase_value,total_frequency,product_diversity,Plan,subscription_duration_days,subscription_age_days,is_active,total_interactions,total_late_payments,payment_count,late_payment_rate,payment_risk_score,PageViews,TimeSpent(minutes),engagement_ratio,engagement_intensity,total_actions,add_to_cart_count,search_count,click_count,unique_pages,cart_conversion_rate,search_intensity,page_diversity,Logins,frequency_score,engagement_score,avg_rating,avg_comment_length,sentiment_score,is_negative,is_positive,emails_sent,emails_opened,emails_clicked,open_rate,click_rate,click_through_rate,marketing_engagement,ChurnLabel,Recency,Frequency,Monetary,r_score,f_score,m_score,rfm_score,rfm_segment,Gender_Female,Gender_Male,Segment_Segment A,Segment_Segment B,Segment_Segment C,nps_category_Detractor,nps_category_Passive,nps_category_Promoter,days_since_last_interaction
0,1001,31,3,1069,0,3994.72,38,7,2689.622546,871,937,0,4,40,3,10.00,400.00,49,15,0.300000,735,24,8,12,4,13,0.320000,0.480000,0.520000,19,4,76,1.0,96.0,0.2,1,0,8,8,8,0.888889,0.888889,0.888889,0.790123,1,523,722,3994.72,1,4,4,9,4,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,523
1,1002,66,6,1455,2,2844.35,4,3,2828.649426,290,529,0,19,10,3,2.50,25.00,100,9,0.089109,900,24,8,7,9,13,0.320000,0.280000,0.520000,9,4,36,2.0,108.0,0.4,1,0,9,9,9,0.900000,0.900000,0.900000,0.810000,0,17,36,2844.35,5,1,3,9,4,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,17
2,1003,36,3,1341,1,1866.52,14,3,2790.271692,319,1184,0,3,8,3,2.00,16.00,1,97,48.500000,97,12,2,7,3,7,0.153846,0.538462,0.538462,19,1,19,4.0,72.0,0.8,0,1,8,8,8,0.888889,0.888889,0.888889,0.790123,0,360,266,1866.52,1,3,2,6,3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,360
3,1004,62,1,1033,2,1378.64,28,5,2905.696003,803,1083,0,59,79,3,19.75,1560.25,25,31,1.192308,775,47,15,16,16,14,0.312500,0.333333,0.291667,4,30,120,1.0,78.0,0.2,1,0,10,10,10,0.909091,0.909091,0.909091,0.826446,1,50,112,1378.64,3,2,2,7,4,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,50
4,1005,68,3,1366,2,2425.05,39,6,2714.759176,580,633,0,10,2,3,0.50,1.00,77,51,0.653846,3927,30,17,4,9,12,0.548387,0.129032,0.387097,12,4,48,3.0,99.0,0.6,0,0,7,7,7,0.875000,0.875000,0.875000,0.765625,0,11,468,2425.05,5,3,3,11,2,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12478,13479,55,8,338,2,1196.56,14,3,2790.271692,745,1296,0,10,3,3,0.75,2.25,70,57,0.802817,3990,6,4,1,1,6,0.571429,0.142857,0.857143,22,30,660,2.0,37.0,0.4,1,0,4,4,4,0.800000,0.800000,0.800000,0.640000,0,82,308,1196.56,3,3,2,8,4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,82
12479,13480,29,7,930,0,710.57,1,1,2859.778143,18,22,0,3,6,3,1.50,9.00,71,66,0.916667,4686,9,3,3,3,8,0.300000,0.300000,0.800000,25,4,100,3.0,102.0,0.6,0,0,7,7,7,0.875000,0.875000,0.875000,0.765625,0,55,25,710.57,3,1,1,5,3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,55
12480,13481,38,1,809,1,5154.42,63,10,2723.138567,20,546,0,26,83,3,20.75,1722.25,96,1,0.010309,96,26,10,11,5,9,0.370370,0.407407,0.333333,9,1,9,5.0,134.0,1.0,0,1,5,5,5,0.833333,0.833333,0.833333,0.694444,1,22,567,5154.42,4,4,5,13,1,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,22
12481,13482,26,0,920,0,6055.16,58,9,2816.218537,484,894,0,13,67,3,16.75,1122.25,63,2,0.031250,126,38,7,15,16,12,0.179487,0.384615,0.307692,2,1,2,5.0,113.0,1.0,0,1,1,1,1,0.500000,0.500000,0.500000,0.250000,0,45,116,6055.16,3,2,5,10,2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,45
12482,13483,29,2,170,0,154.20,1,1,2850.765113,266,499,0,7,49,3,12.25,600.25,93,6,0.063830,558,32,13,10,9,13,0.393939,0.303030,0.393939,6,4,24,3.0,121.0,0.6,0,0,5,5,5,0.833333,0.833333,0.833333,0.694444,1,203,6,154.20,1,1,1,3,0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,203

In [74]:
# Logistic Regression (Target Variable: ChurnLabel)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
X = data.drop(columns=['ChurnLabel', 'CustomerID'], axis=1)
y = data['ChurnLabel']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

# Initialize and train the Logistic Regression model
logreg = LogisticRegression(max_iter=2000, random_state=42)
logreg.fit(X_train, y_train)
# Make predictions on the test set
y_pred = logreg.predict(X_test)
# Evaluate the model
from sklearn.metrics import confusion_matrix, classification_report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")

Confusion Matrix:
[[1208   26]
 [  33 1230]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1234
           1       0.98      0.97      0.98      1263

    accuracy                           0.98      2497
   macro avg       0.98      0.98      0.98      2497
weighted avg       0.98      0.98      0.98      2497

Accuracy: 97.64%

c:\Users\bubut\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [43]:
pd.set_option('display.max_columns', None)  # Show all columns when displaying DataFrame

# Feature Selection

### Mutual Information

In [ ]:
# Feature Selection Using Mutual Information
from sklearn.feature_selection import mutual_info_classif

mutual_data = data.copy()

target = mutual_data['ChurnLabel'] 
features = mutual_data.drop(columns=['ChurnLabel', 'CustomerID'], axis = 1) #1 means y-axis or column and 0 means x-axis or row

mi_scores = mutual_info_classif(features, target)

In [ ]:
mi_df = pd.DataFrame({
    'Feature': features.columns,
    'Score': mi_scores
})


# Select top features based on mutual information scores
top_features = mi_df[mi_df['Score'] > 0]['Feature'].tolist()

mutual_data = mutual_data[['CustomerID'] + top_features + ['ChurnLabel']]
mutual_data.head()

,CustomerID,NPS,total_purchase_value,Plan,subscription_duration_days,is_active,total_interactions,total_late_payments,late_payment_rate,payment_risk_score,PageViews,TimeSpent(minutes),engagement_ratio,engagement_intensity,add_to_cart_count,search_count,click_count,unique_pages,page_diversity,Logins,frequency_score,avg_comment_length,click_through_rate,marketing_engagement,Recency,Monetary,r_score,f_score,rfm_score,rfm_segment,Gender_Male,Segment_Segment C,nps_category_Detractor,nps_category_Passive,nps_category_Promoter,days_since_last_interaction,ChurnLabel
0,1001,3,3994.72,2689.622546,871,0,4,40,10.00,400.00,49,15,0.300000,735,8,12,4,13,0.520000,19,4,96.0,0.888889,0.790123,523,3994.72,1,4,9,4,1.0,0.0,1.0,0.0,0.0,523,1
1,1002,6,2844.35,2828.649426,290,0,19,10,2.50,25.00,100,9,0.089109,900,8,7,9,13,0.520000,9,4,108.0,0.900000,0.810000,17,2844.35,5,1,9,4,0.0,1.0,1.0,0.0,0.0,17,0
2,1003,3,1866.52,2790.271692,319,0,3,8,2.00,16.00,1,97,48.500000,97,2,7,3,7,0.538462,19,1,72.0,0.888889,0.790123,360,1866.52,1,3,6,3,0.0,0.0,1.0,0.0,0.0,360,0
3,1004,1,1378.64,2905.696003,803,0,59,79,19.75,1560.25,25,31,1.192308,775,15,16,16,14,0.291667,4,30,78.0,0.909091,0.826446,50,1378.64,3,2,7,4,0.0,1.0,1.0,0.0,0.0,50,1
4,1005,3,2425.05,2714.759176,580,0,10,2,0.50,1.00,77,51,0.653846,3927,17,4,9,12,0.387097,12,4,99.0,0.875000,0.765625,11,2425.05,5,3,11,2,0.0,1.0,1.0,0.0,0.0,11,0

In [77]:
mi_df.sort_values(by='Score', ascending=False)

                        Feature     Score
12          total_late_payments  0.577530
15           payment_risk_score  0.576667
14            late_payment_rate  0.575771
11           total_interactions  0.282925
17           TimeSpent(minutes)  0.268610
1                           NPS  0.232274
19         engagement_intensity  0.140724
18             engagement_ratio  0.138208
56       nps_category_Detractor  0.106610
46                      r_score  0.061230
59  days_since_last_interaction  0.061009
57         nps_category_Passive  0.060404
43                      Recency  0.057090
58        nps_category_Promoter  0.030983
49                    rfm_score  0.018507
50                  rfm_segment  0.017429
28                       Logins  0.007934
29              frequency_score  0.007291
22                 search_count  0.006741
27               page_diversity  0.005698
55            Segment_Segment C  0.004904
21            add_to_cart_count  0.004721
23                  click_count  0.004620
8    subscription_duration_days  0.003952
7                          Plan  0.003724
10                    is_active  0.003261
42         marketing_engagement  0.003114
24                 unique_pages  0.002938
16                    PageViews  0.002644
47                      f_score  0.002421
52                  Gender_Male  0.002086
4          total_purchase_value  0.002057
45                     Monetary  0.001835
32           avg_comment_length  0.001222
41           click_through_rate  0.000759
25         cart_conversion_rate  0.000000
0                           Age  0.000000
2              account_age_days  0.000000
20                total_actions  0.000000
13                payment_count  0.000000
3                     age_group  0.000000
5               total_frequency  0.000000
6             product_diversity  0.000000
9         subscription_age_days  0.000000
26             search_intensity  0.000000
37                emails_opened  0.000000
40                   click_rate  0.000000
39                    open_rate  0.000000
36                  emails_sent  0.000000
33              sentiment_score  0.000000
34                  is_negative  0.000000
35                  is_positive  0.000000
30             engagement_score  0.000000
31                   avg_rating  0.000000
38               emails_clicked  0.000000
44                    Frequency  0.000000
51                Gender_Female  0.000000
48                      m_score  0.000000
54            Segment_Segment B  0.000000
53            Segment_Segment A  0.000000

In [75]:
# Train a Logistic Regression model using only the selected features
X_mutual = mutual_data.drop(columns=['ChurnLabel', 'CustomerID'], axis=1)
y_mutual = mutual_data['ChurnLabel']

# Train-test split
X_train_mutual, X_test_mutual, y_train_mutual, y_test_mutual = train_test_split(X_mutual, y_mutual, test_size=0.2, random_state=42, stratify=y_mutual)
logreg_mutual = LogisticRegression(max_iter=2000, random_state=42)
logreg_mutual.fit(X_train_mutual, y_train_mutual)

# Predictions and evaluation
y_pred_mutual = logreg_mutual.predict(X_test_mutual)
print("Confusion Matrix (Mutual Information):")
print(confusion_matrix(y_test_mutual, y_pred_mutual))
print("\nClassification Report (Mutual Information):")
print(classification_report(y_test_mutual, y_pred_mutual))
print(f"Accuracy (Mutual Information): {accuracy_score(y_test_mutual, y_pred_mutual) * 100:.2f}%")

Confusion Matrix (Mutual Information):
[[1208   26]
 [  33 1230]]

Classification Report (Mutual Information):
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1234
           1       0.98      0.97      0.98      1263

    accuracy                           0.98      2497
   macro avg       0.98      0.98      0.98      2497
weighted avg       0.98      0.98      0.98      2497

Accuracy (Mutual Information): 97.64%

c:\Users\bubut\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### Intuition

In [79]:
# Feature Selection Based on Intuition
# I will select them by removing features with an MI score of less than 0.01
intuitive_features = mi_df[mi_df['Score'] >= 0.01]['Feature'].tolist()
intuitive_data = data[['CustomerID'] + intuitive_features + ['ChurnLabel']]
intuitive_data.head()

# Train a Logistic Regression model using only the intuitively selected features
X_intuitive = intuitive_data.drop(columns=['ChurnLabel', 'CustomerID'], axis=1)
y_intuitive = intuitive_data['ChurnLabel']

# Train-test split
X_train_intuitive, X_test_intuitive, y_train_intuitive, y_test_intuitive = train_test_split(X_intuitive, y_intuitive, test_size=0.2, random_state=42, stratify=y_intuitive)

# Initialize and train the Logistic Regression model
logreg_intuitive = LogisticRegression(max_iter=2000, random_state=42)
logreg_intuitive.fit(X_train_intuitive, y_train_intuitive)
# Predictions and evaluation
y_pred_intuitive = logreg_intuitive.predict(X_test_intuitive)
print("Confusion Matrix (Intuitive Selection):")
print(confusion_matrix(y_test_intuitive, y_pred_intuitive))
print("\nClassification Report (Intuitive Selection):")
print(classification_report(y_test_intuitive, y_pred_intuitive))
print(f"Accuracy (Intuitive Selection): {accuracy_score(y_test_intuitive, y_pred_intuitive) * 100:.2f}%")

Confusion Matrix (Intuitive Selection):
[[1208   26]
 [  33 1230]]

Classification Report (Intuitive Selection):
              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1234
           1       0.98      0.97      0.98      1263

    accuracy                           0.98      2497
   macro avg       0.98      0.98      0.98      2497
weighted avg       0.98      0.98      0.98      2497

Accuracy (Intuitive Selection): 97.64%

c:\Users\bubut\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(